### PR TITLE
Don't build packages as root

### PR DESCRIPTION
**Pull request by jefferyto**
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
This fixes the CI errors in https://github.com/openwrt/packages/pull/18293.

**Comment by jefferyto** [comment]
Ping @aparcar

**Comment by ynezz** [comment]
Thanks, [seems to work](https://github.com/ynezz/openwrt-packages/actions/runs/2326622761) so LGTM.

**Comment by aparcar** [comment]
Thanks!

**Comment by jefferyto** [comment]
Would appreciate it if someone can tag this version so it can be used in the packages repo.

**Comment by aparcar** [comment]
I added v5.1 and updated v5 to the HEAD

**Pull request merged**
