### PR TITLE
run init scripts through shfmt

### PR DESCRIPTION
**Pull request by neheb**
Based on the quilt check above.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
You should pass the NO_SHFMT_CHECK [here](https://github.com/openwrt/gh-action-sdk/blob/master/action.yml) as well.

**Comment by neheb** [comment]
Done.

**Review by aparcar — APPROVED** [review]

**Comment by aparcar** [comment]
@jefferyto @neheb mind creating a PR?

**Comment by neheb** [comment]
> 

Nope. Needs testing. My bullseye setup doesn't have it.

**Comment by BKPepe** [comment]
Well, after 4 years, the issue reported by @jefferyto is appearing again, and it's starting out nicely with zabbix. :-)

I'll try to look into why it can't find shfmt, see https://github.com/openwrt/packages/pull/29803#issuecomment-4787551913

**Pull request merged**
